# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 15:42
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='title')),
                ('post', ckeditor.fields.RichTextField(verbose_name='post')),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='published time')),
                ('slug', models.SlugField(blank=True)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name_plural': 'Posts',
                'ordering': ['-published'],
                'verbose_name': 'Post',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
            ],
            options={
                'verbose_name_plural': 'Subscribers',
                'verbose_name': 'Subscriber',
            },
        ),
    ]
